refactor chaincode operator
SubstraFoundation/hlf-k8s pull request #103
Opened 2020-12-01 21:01 UTC by AurelienGasser

This PR moves the following calls from the appchannel operator to the chaincode operator, which removes a bit of  code/complexity.

```
lifecycle chaincode checkcommitreadiness
peer lifecycle chaincode querycommitted
peer chaincode invoke --isInit
```

2020-12-02 08:16 UTC, ClementGautier submitted a review, later dismissed
Looks great !

2020-12-02 08:20 UTC, ClementGautier commented
Regarding your question on the arguments I'd say: use env variables when possible to keep the code easy to read and maintain. Basically use CORE_PEER_ADDRESS / CORE_PEER_TLS_ROOTCERT_FILE etc.
![image](https://user-images.githubusercontent.com/660091/100847110-a8a7eb00-347f-11eb-9c3d-f9c0f099f42a.png)

2020-12-02 08:40 UTC, Kelvin-M requested changes
Nice work, but your `Side note about explicit v.s. implicit options` is not really true ^^

I think you read my [suggestion](https://github.com/SubstraFoundation/hlf-k8s/pull/102#issuecomment-734149787) too quickly, or maybe I don't explain the idea properly. You're confusing `core.yaml` default values to connect to **a** Peer with `--peerAddresses` `--tlsRootCertFiles` to endorse **a** Peer transaction by multiple  external Peer**s**

`--peerAddresses` `--tlsRootCertFiles` is not just two arguments encapsulated in $ENDORSEMENT, it's repeated (`--peerAddresses` `--tlsRootCertFiles`) along all Peers connection like for a Peer1 which try to endorse chaincode commit:

`ENDORSEMENT="--peerAddresses Peer2:7054 --tlsRootCertFiles tlsRootCert-Peer2.crt --peerAddresses Peer3:7054 --tlsRootCertFiles tlsRootCert-Peer3.crt --peerAddresses Peer4:7054 --tlsRootCertFiles tlsRootCert-Peer4.crt"`

You may have not seen any issue because for multiple examples (2 orgs no ca, 2 orgs, 4 orgs), and by default in `configmap-fabric.yaml`, chaincode lifecycle policy is `ANY`
```
      Policies: &ApplicationDefaultPolicies
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "ANY Endorsement"
```

But, for 3 or 4 Orgs majority example, your code won't work, as transaction will be only endorsed by one Peer (itself) , chaincode lifecycle policy is `MAJORITY`
```
appPolicies: |-
    LifecycleEndorsement:
        Type: ImplicitMeta
        Rule: "MAJORITY Endorsement"
```

2020-12-03 08:43 UTC, Kelvin-M commented on charts/hlf-k8s/templates/deployment-chaincode-operator.yaml
> +                      --signature-policy "OR('MyOrg1MSP.member','MyOrg2MSP.member','MyOrg3MSP.member','MyOrg4MSP.member')" \
Hardcoded policy ?

2020-12-03 08:44 UTC, Kelvin-M commented on charts/hlf-k8s/templates/deployment-chaincode-operator.yaml
> +                      -o network-orderer-hlf-ord.orderer:7050 \
Hardcoded orderer ?

2020-12-03 08:44 UTC, Kelvin-M commented on charts/hlf-k8s/templates/deployment-chaincode-operator.yaml
> +                      --channelID mychannel \
Channel and chaincode properties are hardcoded !

2020-12-03 22:48 UTC, AurelienGasser commented
This is ready for another review

e2e tests: :heavy_check_mark: 

@Kelvin-M as discussed, I extracted the `sequence` changes and moved them to a [new PR](https://github.com/SubstraFoundation/hlf-k8s/pull/107) (I'll let you take it up from there)

2020-12-04 08:34 UTC, ClementGautier approved these changes

2020-12-07 08:11 UTC, Kelvin-M submitted a review, later dismissed

2020-12-07 08:35 UTC, Kelvin-M commented
Rebased

2020-12-07 09:33 UTC, Kelvin-M approved these changes

2020-12-07 09:58 UTC, ClementGautier approved these changes

2020-12-07 10:09 UTC, merged