[chaincode-operator] fix multi approval
SubstraFoundation/hlf-k8s pull request #116
Opened 2021-01-11 14:56 UTC by mblottiere

Due to way condition were written, there was an approval issued on each iteration (approximately every 10s).
This was generating a new transaction each time, increasing block height although there was no real chaincode usage.

With these changes, the loop body is only executed when the condition is met.

2021-01-11 15:07 UTC, AurelienGasser commented
LGTM :+1: 

- You need to bump the chart version (`Chart.yaml`) since there's a modification of one of the template files of the chart
- Nit: IMO it would be clearer (and could potentially help debugging) if the files (e.g. `chaincode.approve`) always included the chaincode name and version (e.g. `chaincode_{{ .name }}_{{ .version }}.approve`

2021-01-11 15:10 UTC, AlexandrePicosson requested changes
Good catch, LGTM !

You should bump the chart version here for the users to know that there is a fix available: https://github.com/SubstraFoundation/hlf-k8s/blob/b02c855b5ada981e3b3cd5e464fb0b20e441b7fc/charts/hlf-k8s/Chart.yaml#L18

2021-01-11 16:53 UTC, AurelienGasser commented on charts/hlf-k8s/templates/deployment-chaincode-operator.yaml
> +                until grep -q "true" chaincode.{{ .name }}.ready; do
I think the `version` should also appear here, unless I'm missing a reason to omit it?

2021-01-11 21:06 UTC, AurelienGasser approved these changes
LGTM

e2e tests: :heavy_check_mark:

2021-01-12 07:36 UTC, Kelvin-M approved these changes

2021-01-12 08:28 UTC, merged